apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray111
  template:
    metadata:
      labels:
        app: ray111
    spec:
      containers:
      - image: okteto.dev/ray111:latest
        name: ray111
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6b618a8b-1952-4e39-a8f8-324aee17780f"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "6b618a8b-1952-4e39-a8f8-324aee17780f"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
