apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray222
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray222
  template:
    metadata:
      labels:
        app: ray222
    spec:
      containers:
      - image: okteto.dev/ray222:latest
        name: ray222
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "5bc1e65b-76cd-4e6a-b02c-601a97057e6f"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "5bc1e65b-76cd-4e6a-b02c-601a97057e6f"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
