apiVersion: v1
kind: Service
metadata:
  name: ray222
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ray222"
    port: 8080
  selector:
    app: ray222
