apiVersion: v1
kind: Service
metadata:
  name: ray111
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ray111"
    port: 8080
  selector:
    app: ray111
